# Generated by Django 4.1.2 on 2022-10-07 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=150, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['category_title'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('сourse_title', models.CharField(max_length=150, verbose_name='Название курса')),
                ('course_icon', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Иконка курса')),
                ('course_description', models.TextField(max_length=250, verbose_name='Описание курса')),
                ('course_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('course_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blablycode_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-course_created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=150, verbose_name='Название курса')),
                ('lesson_video', models.CharField(max_length=150, verbose_name='Видео')),
                ('lesson_description', models.TextField(max_length=150, verbose_name='Описание урока')),
                ('lesson_exercise', models.TextField(max_length=500, verbose_name='Задание урока')),
                ('lesson_homework', models.TextField(max_length=500, verbose_name='Домашнее задание')),
                ('lesson_code_editor', models.CharField(max_length=150, verbose_name='Редактор кода')),
                ('lesson_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('lesson_сourse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blablycode_app.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Видеоурок',
                'verbose_name_plural': 'Видеоуроки',
                'ordering': ['-lesson_created_at'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_title', models.CharField(blank=True, default='Домашнее задание', max_length=50, verbose_name='Домашнее задание')),
                ('homework_author', models.CharField(max_length=100, verbose_name='Выполнил')),
                ('homework_file', models.FileField(upload_to='files/%Y/%m/%d/', verbose_name='Файл')),
                ('homework_verified', models.BooleanField(blank=True, verbose_name='Проверено')),
                ('homework_comment', models.TextField(blank=True, max_length=250, verbose_name='Комментарий к заданию')),
                ('homework_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blablycode_app.course', verbose_name='Курс')),
                ('homework_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blablycode_app.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
    ]
