# Generated by Django 4.1.2 on 2022-10-11 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blablycode_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_title', models.CharField(max_length=50, verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Возраст',
                'verbose_name_plural': 'Возраст',
                'ordering': ['age_title'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_age',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blablycode_app.age', verbose_name='Возраст'),
        ),
    ]
