# Generated by Django 4.1.2 on 2022-10-11 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blablycode_app', '0002_age_course_course_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('article_content', models.TextField(max_length=2500, verbose_name='Содержание')),
                ('article_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('article_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('article_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blablycode_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-article_created_at'],
            },
        ),
    ]
