# Generated by Django 3.2.5 on 2023-03-19 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blablycode_app', '0004_auto_20230303_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['lesson_created_at'], 'verbose_name': 'Видеоурок', 'verbose_name_plural': 'Видеоуроки'},
        ),
        migrations.AlterField(
            model_name='homework',
            name='homework_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to=settings.AUTH_USER_MODEL, verbose_name='Выполнил'),
        ),
    ]
