# Generated by Django 3.2.5 on 2023-03-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablycode_app', '0005_auto_20230319_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_comment',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Комментарий к заданию'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homework_verified',
            field=models.BooleanField(blank=True, null=True, verbose_name='Проверено'),
        ),
    ]
